version: "3.8"

services:
  scraper-web-remote:
    build: .
    ports:
      - "${PORT}:${PORT}"
    environment:
      - NODE_ENV=production
    container_name: scraper-web-remote
    restart: on-failure
    networks:
      - server-network

networks:
  server-network:
    external: true

