version: "3.8"

services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_BACKEND_URL=http://127.0.0.1:8000
      - NEXT_PUBLIC_IMAGE1_URL=animeflv.net
      - NEXT_PUBLIC_IMAGE2_URL=www3.animeflv.net
    container_name: web